### PR TITLE
fix(agama-pw): Application throws a null exception for unregistered users

### LINKED ISSUE #37: fix(agama-pw): Application throws a null exception for unregistered users
When `enableLock` is set to `true`, the application throws a null pointer exception if the user is not registered

```
{
 "org.gluu.agama.pw.main": {
   "maxLoginAttempt": 6,
   "enableLock": true,
   "lockExpTime": 180
 }
}
```

### PR DESCRIPTION
**Pull request by mmrraju**
close #37 and #39

### CODE REVIEW

File: lib/org/gluu/agama/pw/jans/JansPasswordService.java [hunk 1]
```diff
@@ -56,6 +56,10 @@ public boolean validate(String username, String password) {
     @Override
     public String lockAccount(String username) {
         User currentUser = userService.getUser(username);
+        if (currentUser == null) {
+            LogUtils.log("User % not found. Cannot lock account.", username);
+            return "User not found. Cannot proceed with account lock.";
```
Comment (ossdhaval) [inline lib/org/gluu/agama/pw/jans/JansPasswordService.java]: Relevant if this is message is going to show up on the UI.

This message confirms that `user is not available in the system`. Ideally, if the someone is trying to enter username and password, we should just say authentication failed, without telling that this user doesn't exist.

**Review by ossdhaval — APPROVED** [review]

File: lib/org/gluu/agama/pw/jans/JansPasswordService.java (hunk 1 above)
Comment (ossdhaval) [reply lib/org/gluu/agama/pw/jans/JansPasswordService.java]: @mmrraju Has this been taken care?

Comment (mmrraju) [reply lib/org/gluu/agama/pw/jans/JansPasswordService.java]: > This message confirms that `user is not available in the system`. Ideally, if the someone is trying to enter username and password, we should just say authentication failed, without telling that this user doesn't exist.

Yes, I'm changing the message

**Comment by ossdhaval** [comment]
@syntrydy Please help with review to move this forward.

**Comment by ossdhaval** [comment]
@mmrraju This PR now contains more number of changes. I would recommend:

- Get this reviewed by @jgomer2001 for Agama related changes
- Get this PR merged at the earliest. If there are more changes, push them as follow up PRs.

**Review by jgomer2001 — APPROVED** [review]
